name = "QuantumAnnealers"
uuid = "bc34ea60-eb94-4a6e-8583-dd13eb84e3c4"
authors = ["J. Quetzalcoatl, Jorge FdCD"]
version = "1.0.0-DEV"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
